const FETCH_ALL_TASKS_INIT = "FETCH_ALL_TASKS_INIT";
const FETCH_ALL_TASKS_SUCCESS = "FETCH_ALL_TASKS_SUCCESS";
const FETCH_ALL_TASKS_FAIL = "FETCH_ALL_TASKS_FAIL";

const CREATE_NEW_TASK_INIT = "CREATE_NEW_TASK_INIT";
const CREATE_NEW_TASK_SUCCESS = "CREATE_NEW_TASK_SUCCESS";
const CREATE_NEW_TASK_FAIL = "CREATE_NEW_TASK_FAIL";

const TOGGLE_STATUS = "TOGGLE_STATUS";

const DELETE_TASK = "DELETE_TASK";

const CLOSE_MODAL = "CLOSE_MODAL";

const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

const TOGGLE_MEMBERSHIP = "TOGGLE_MEMBERSHIP";

export {
  FETCH_ALL_TASKS_INIT,
  FETCH_ALL_TASKS_SUCCESS,
  FETCH_ALL_TASKS_FAIL,
  CREATE_NEW_TASK_INIT,
  CREATE_NEW_TASK_SUCCESS,
  CREATE_NEW_TASK_FAIL,
  TOGGLE_STATUS,
  DELETE_TASK,
  CLOSE_MODAL,
  LOGIN_USER_SUCCESS,
  LOGIN_USER_FAIL,
  TOGGLE_MEMBERSHIP,
  REGISTER_USER_SUCCESS,
  REGISTER_USER_FAIL,
};
